parameters:
    json_schemas_path:
        - "%kernel.project_dir%/config/json/schema"

imports:
    - { resource: 'services/' }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
